### ISSUE TITLE
How to fix this

### ISSUE THREAD

**Issue by onephones** [codehasan/dex2c#10]
PS C:\Users\bualt\PycharmProjects\dex2c> python3 dcc.py -a test.apk -o output.apk
Traceback (most recent call last):
  File "C:\Users\bualt\PycharmProjects\dex2c\dcc.py", line 14, in <module>
    from androguard.core.analysis import analysis
  File "C:\Users\bualt\PycharmProjects\dex2c\androguard\core\analysis\analysis.py", line 8, in <module>
    from androguard.core.bytecodes import dvm
  File "C:\Users\bualt\PycharmProjects\dex2c\androguard\core\bytecodes\dvm.py", line 8, in <module>
    from androguard.core.bytecodes.apk import APK
  File "C:\Users\bualt\PycharmProjects\dex2c\androguard\core\bytecodes\apk.py", line 7, in <module>
    from androguard.util import read, get_certificate_name_string
  File "C:\Users\bualt\PycharmProjects\dex2c\androguard\util.py", line 1, in <module>
    import asn1crypto
ModuleNotFoundError: No module named 'asn1crypto'

**Comment by codehasan** [comment]
Run the following command.
`pip install asn1crypto`

If such issues occur again, such as ModuleNotFoundError. Search the module's name in google about how to install it. With that your problem should be solved.
