### ISSUE TITLE
apktool error

### ISSUE THREAD

**Issue by adhksosne** [codehasan/dex2c#21]
[ERROR   ] dcc: Compile input.apk failed!
Traceback (most recent call last):
  File "D:\dex2c-master\dcc.py", line 1017, in <module>
    dcc_main(
  File "D:\dex2c-master\dcc.py", line 786, in dcc_main
    decompiled_dir = ApkTool.decompile(apkfile)
  File "D:\dex2c-master\dcc.py", line 116, in decompile
    check_call([APKTOOL2, 'd', '-r', '-f', '-o', outdir, apk])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tools/apktool.bat', 'd', '-r', '-f', '-o', '.tmp\\dcc-apktool-4iKgmTdI', 'input.apk']' returned non-zero exit status 1.
Command '['tools/apktool.bat', 'd', '-r', '-f', '-o', '.tmp\\dcc-apktool-4iKgmTdI', 'input.apk']' returned non-zero exit status 1.

**Comment by NoName1510** [comment]
How to fix it

**Comment by adhksosne** [comment]
> How to fix it

Look here, https://github.com/codehasan/dex2c/issues/13
