### ISSUE TITLE
Termux android error

### ISSUE THREAD

**Issue by NoName1510** [codehasan/dex2c#27]
make: Leaving directory '/data/data/com.termux/files/home/dex2c/.tmp/dcc-project-eQ3UZ4LF'                      tools/apktool: line 77: exec: java: not found           [ERROR   ] dcc: Compile fb64.apk failed!
Traceback (most recent call last):                        File "/data/data/com.termux/files/home/dex2c/dcc.py", line 1014, in <module>
    dcc_main(                                             File "/data/data/com.termux/files/home/dex2c/dcc.py", line 783, in dcc_main
    decompiled_dir = ApkTool.decompile(apkfile)                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/dex2c/dcc.py", line 118, in decompile
    check_call(['bash', APKTOOL3, 'd', '-r', '-f', '-o', outdir, apk])
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)              subprocess.CalledProcessError: Command '['bash', 'tools/apktool', 'd', '-r', '-f', '-o', '.tmp/dcc-apktool-ZU6r9vxB', 'fb64.apk']' returned non-zero exit status 127.   Command '['bash', 'tools/apktool', 'd', '-r', '-f', '-o', '.tmp/dcc-apktool-ZU6r9vxB', 'fb64.apk']' returned non-zero exit status 127.
[INFO    ] dcc: Restoring jni folder                    [INFO    ] dcc: Removing .tmp folder

**Comment by NoName1510** [comment]
Fix by instal java
